# Generated by Django 4.1.5 on 2023-01-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccines',
            new_name='Vaccine',
        ),
    ]
